import json

# Define the detailed information for each website
websites_info = [
    {"url": "https://condehouse2.myshopify.com", "description": "Modern furniture crafted in Japan", "price_range": "high (above $1000)"},
    {"url": "https://pythonperformanceus.myshopify.com", "description": "Python performance products", "price_range": "medium ($100-$500)"},
    {"url": "https://zositech.myshopify.com", "description": "Tech gadgets and accessories", "price_range": "medium ($100-$500)"},
    {"url": "https://anson.myshopify.com", "description": "Custom jewelry and accessories", "price_range": "high (above $1000)"},
    {"url": "https://pergamino2020co.myshopify.com", "description": "Specialty coffee and accessories", "price_range": "medium ($100-$500)"},
    {"url": "https://deparre.myshopify.com", "description": "Fashion clothing and accessories", "price_range": "medium ($100-$500)"},
    {"url": "https://bktt.myshopify.com", "description": "Bike parts and accessories", "price_range": "medium ($100-$500)"},
    {"url": "https://maanfarms.myshopify.com", "description": "Farm produce and products", "price_range": "low (below $100)"},
    {"url": "https://durstongear.myshopify.com", "description": "Outdoor gear and equipment", "price_range": "high (above $1000)"},
    {"url": "https://bandidospitstop1.myshopify.com", "description": "Automotive parts and accessories", "price_range": "medium ($100-$500)"},
    {"url": "https://sonidoseguro.myshopify.com", "description": "Secure audio equipment", "price_range": "medium ($100-$500)"},
    {"url": "https://aus.myshopify.com", "description": "General merchandise store", "price_range": "varied"},
    {"url": "https://tellenzi.myshopify.com", "description": "Fashion and accessories", "price_range": "medium ($100-$500)"},
    {"url": "https://elclan.myshopify.com", "description": "Latin American fashion", "price_range": "medium ($100-$500)"},
    {"url": "https://401games.myshopify.com", "description": "Board games and accessories", "price_range": "medium ($100-$500)"},
    {"url": "https://mushqus.myshopify.com", "description": "Custom plush toys", "price_range": "low (below $100)"},
    {"url": "https://prajaktaraj.myshopify.com", "description": "Indian ethnic wear", "price_range": "medium ($100-$500)"},
    {"url": "https://bennettsbutchers.myshopify.com", "description": "Butcher shop products", "price_range": "medium ($100-$500)"},
    {"url": "https://carnivoresnax.myshopify.com", "description": "Meat snacks and jerky", "price_range": "medium ($100-$500)"},
    {"url": "https://keepgo.myshopify.com", "description": "Travel SIM cards and WiFi", "price_range": "medium ($100-$500)"},
    {"url": "https://sbfk.myshopify.com", "description": "Kids fashion and accessories", "price_range": "medium ($100-$500)"},
    {"url": "https://jcardiecast.myshopify.com", "description": "Diecast model cars", "price_range": "medium ($100-$500)"},
    {"url": "https://sqirl.myshopify.com", "description": "Specialty jams and preserves", "price_range": "medium ($100-$500)"},
    {"url": "https://happymugcoffee.myshopify.com", "description": "Specialty coffee beans", "price_range": "medium ($100-$500)"},
    {"url": "https://inverfin.myshopify.com", "description": "Financial services and products", "price_range": "varied"},
    {"url": "https://cosplaymax.myshopify.com", "description": "Cosplay costumes and accessories", "price_range": "medium ($100-$500)"},
    {"url": "https://gbwearbrasil.myshopify.com", "description": "Brazilian fitness wear", "price_range": "medium ($100-$500)"},
    {"url": "https://fangamer.myshopify.com", "description": "Video game merchandise", "price_range": "medium ($100-$500)"},
    {"url": "https://sharkbanzusa.myshopify.com", "description": "Shark deterrent bands", "price_range": "medium ($100-$500)"},
    {"url": "https://aandfonlinestore.myshopify.com", "description": "Fashion clothing and accessories", "price_range": "medium ($100-$500)"},
    {"url": "https://logopk.myshopify.com", "description": "Promotional products and clothing", "price_range": "medium ($100-$500)"},
    {"url": "https://champagnesaturdays.myshopify.com", "description": "Champagne and accessories", "price_range": "high (above $1000)"},
    {"url": "https://eosjwt.myshopify.com", "description": "Jewelry and watches", "price_range": "high (above $1000)"},
    {"url": "https://ruslanbaginskiy.myshopify.com", "description": "Designer hats and accessories", "price_range": "high (above $1000)"},
    {"url": "https://bleeperactive.myshopify.com", "description": "Activewear and fitness gear", "price_range": "medium ($100-$500)"},
    {"url": "https://shoppremiumoutlets.myshopify.com", "description": "Outlet store products", "price_range": "varied"},
    {"url": "https://farer.myshopify.com", "description": "Watches and accessories", "price_range": "high (above $1000)"},
    {"url": "https://shaperepublic.myshopify.com", "description": "Nutritional supplements", "price_range": "medium ($100-$500)"},
    {"url": "https://swiftindi.myshopify.com", "description": "Indian spices and food products", "price_range": "medium ($100-$500)"},
    {"url": "https://farmacorp.myshopify.com", "description": "Pharmacy products", "price_range": "varied"},
    {"url": "https://ringrover.myshopify.com", "description": "Phone cases and accessories", "price_range": "medium ($100-$500)"},
    {"url": "https://mariscalmodahombre.myshopify.com", "description": "Men's fashion", "price_range": "medium ($100-$500)"},
    {"url": "https://mumbistore.myshopify.com", "description": "Home decor and accessories", "price_range": "medium ($100-$500)"},
    {"url": "https://phibeach.myshopify.com", "description": "Beachwear and accessories", "price_range": "medium ($100-$500)"},
    {"url": "https://nybooks.myshopify.com", "description": "Books and literary products", "price_range": "medium ($100-$500)"},
    {"url": "https://storefeatheredfriends.myshopify.com", "description": "Outdoor gear and clothing", "price_range": "high (above $1000)"},
    {"url": "https://kahunaverse.myshopify.com", "description": "Sporting goods and equipment", "price_range": "medium ($100-$500)"},
    {"url": "https://alzheimersshop.myshopify.com", "description": "Alzheimer's support products", "price_range": "medium ($100-$500)"},
    {"url": "https://moonmats.myshopify.com", "description": "Outdoor mats and accessories", "price_range": "medium ($100-$500)"},
    {"url": "https://komalaziz.myshopify.com", "description": "Pakistani fashion", "price_range": "medium ($100-$500)"},
    {"url": "https://sntstoredk.myshopify.com", "description": "Danish clothing and accessories", "price_range": "medium ($100-$500)"},
    {"url": "https://muuchstac.myshopify.com", "description": "Men's grooming products", "price_range": "medium ($100-$500)"},
    {"url": "https://firewireusa.myshopify.com", "description": "Surfboards and accessories", "price_range": "high (above $1000)"},
    {"url": "https://switchaprph.myshopify.com", "description": "Switch accessories and gadgets", "price_range": "medium ($100-$500)"}
]

# Save the data to a JSON file
file_path = "./database/websites_info_0704.json"
with open(file_path, "w") as json_file:
    json.dump(websites_info, json_file, indent=4)